/**
 * Database Types
 *
 * This file is auto-generated by Supabase CLI.
 * Run: supabase gen types typescript --project-id dkdxthkhuzgrkzmhmxst > lib/db/database.types.ts
 *
 * Note: Currently contains placeholder types. Generate actual types when needed.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {}
    Views: {}
    Functions: {}
    Enums: {}
  }
}
